Debug

diff --git a/.github/workflows/basic.yml b/.github/workflows/basic.yml
--- a/.github/workflows/basic.yml
+++ b/.github/workflows/basic.yml
@@ -146,7 +146,11 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         python -m pip install jsondiff
-        make test ARGS=-V || (echo "Tests failed!!" && cat /home/runner/work/GenomicsDB/GenomicsDB/build/Testing/Temporary/LastTest.log && exit 1)
+        make test ARGS=-V || (echo "Tests failed!!" &&
+           cat /home/runner/work/GenomicsDB/GenomicsDB/build/Testing/Temporary/LastTest.log &&
+           echo "SureFire reports..." &&
+           cat /home/runner/work/GenomicsDB/GenomicsDB/build/target/surefire-reports/junitreports/TEST-org.genomicsdb.GenomicsDBLibLoaderTest.xml &&
+           echo "SureFire reports DONE" && exit 1)
 
     - name: Test - Distributed FileSystems
       if: matrix.type == 'hdfs'
